/* Eolithic2
 * Copyright 2025-2026 Patrick Derosby
 * Released under the zlib License.
 * See eolithic2.LICENSE for details.
 */

//Defs should be included by including "/engine/utils/Macros.h"

#pragma once

#ifdef EDITOR_MODE

#define DEBUG_DEF_BUILT_WITH_DEBUG_DEFS
#define DEBUG_DEF_ENABLE_CONSOLE_NOTIFICATIONS

//#define DEBUG_DEF_DISABLE_CONTROLLER_SAFETY_CHECKS
//#define DEBUG_DEF_DISABLE_LOW_FPS_READOUT_IN_RECORDING_TOOL
//#define DEBUG_DEF_FORCE_LOWEST_BACK_BUFFER_SIZE
//#define DEBUG_DEF_FORCE_GAME_SPEED_MUL 100
//#define DEBUG_DEF_RUN_THE_GAME_FAST
#define DEBUG_DEF_DISABLE_RECORDING_SAFETY_SAVING
#define DEBUG_DEF_DISABLE_RECORDING_SAFETY_LOADING
#define DEBUG_DEF_DISABLE_RECORDING_SAFETY_ACHIEVEMENTS
#define DEBUG_DEF_DISABLE_RECORDING_SAFETY_LEADERBOARDS
//#define DEBUG_DEF_PLAY_RECORDING
//#define DEBUG_DEF_PLAY_RECORDING_FAST
//#define DEBUG_DEF_SOAK_TEST
//#define DEBUG_SOAK_TEST_FAST
//#define DEBUG_DEF_PLAY_RECORDING_SESSIONS
//#define DEBUG_DEF_PLAY_RECORDING_SESSIONS_FAST
//#define DEBUG_DEF_FORCED_WINDOW_MUL 1
//#define DEBUG_DEF_FORCED_LANGUAGE 1 //EFIGS 01234
//#define DEBUG_DEF_DISABLE_RUMBLE
//#define DEBUG_DEF_DISABLE_AUDIO
//#define DEBUG_DEF_DISABLE_SAVING
//#define DEBUG_DEF_DISABLE_LOADING
//#define DEBUG_DEF_DISABLE_ACHIEVEMENTS
//#define DEBUG_DEF_DISABLE_LEADERBOARDS
//#define DEBUG_DEF_FORCE_VSYNC_OFF
//#define DEBUG_DEF_FORCE_CVAR_SHOW_IN_GAME_TIMER_ON
//#define DEBUG_DEF_FORCE_VSYNC_ON
//#define DEBUG_DEF_FORCE_FULLSCREEN_OFF
//#define DEBUG_DEF_FORCE_FULLSCREEN_ON
//#define DEBUG_DEF_USE_TIME_RANDOM_FOR_SHARED_RANDOM
//#define DEBUG_DEF_MAKE_GAME_ALWAYS_ACTIVE
//#define DEBUG_DEF_AUTO_MODE
//#define DEBUG_DEF_AUTO_MODE_FIXED
//#define DEBUG_DEF_USE_REWIND_TESTER

#ifdef DEBUG_DEF_USE_REWIND_TESTER
#define DEBUG_DEF_REWIND_TESTER_REWIND_INTERVAL (60 * 12)
#define DEBUG_DEF_REWIND_TESTER_REWIND_LENGTH (60 * 4)
#endif

#endif