/* Eolithic2
 * Copyright 2025-2026 Patrick Derosby
 * Released under the zlib License.
 * See eolithic2.LICENSE for details.
 */

#pragma once

#include "stdint.h"

typedef struct IStringArray IStringArray;

#define ACTIONLIST_LENGTH 30
#define ACTIONLIST_GAME_A "GAME_A"
#define ACTIONLIST_GAME_B "GAME_B"
#define ACTIONLIST_GAME_X "GAME_X"
#define ACTIONLIST_GAME_Y "GAME_Y"
#define ACTIONLIST_GAME_LB "GAME_LB"
#define ACTIONLIST_GAME_LT "GAME_LT"
#define ACTIONLIST_GAME_LS "GAME_LS"
#define ACTIONLIST_GAME_RB "GAME_RB"
#define ACTIONLIST_GAME_RT "GAME_RT"
#define ACTIONLIST_GAME_RS "GAME_RS"
#define ACTIONLIST_GAME_START "GAME_START"
#define ACTIONLIST_GAME_SELECT "GAME_SELECT"
#define ACTIONLIST_GAME_LS_UP "GAME_LS_UP"
#define ACTIONLIST_GAME_LS_RIGHT "GAME_LS_RIGHT"
#define ACTIONLIST_GAME_LS_DOWN "GAME_LS_DOWN"
#define ACTIONLIST_GAME_LS_LEFT "GAME_LS_LEFT"
#define ACTIONLIST_GAME_RS_UP "GAME_RS_UP"
#define ACTIONLIST_GAME_RS_RIGHT "GAME_RS_RIGHT"
#define ACTIONLIST_GAME_RS_DOWN "GAME_RS_DOWN"
#define ACTIONLIST_GAME_RS_LEFT "GAME_RS_LEFT"
#define ACTIONLIST_GAME_DIGITAL_UP "GAME_DIGITAL_UP"
#define ACTIONLIST_GAME_DIGITAL_RIGHT "GAME_DIGITAL_RIGHT"
#define ACTIONLIST_GAME_DIGITAL_DOWN "GAME_DIGITAL_DOWN"
#define ACTIONLIST_GAME_DIGITAL_LEFT "GAME_DIGITAL_LEFT"
#define ACTIONLIST_GAME_MENU_SELECT "GAME_MENU_SELECT"
#define ACTIONLIST_GAME_MENU_BACK "GAME_MENU_BACK"
#define ACTIONLIST_GAME_MENU_UP "GAME_MENU_UP"
#define ACTIONLIST_GAME_MENU_RIGHT "GAME_MENU_RIGHT"
#define ACTIONLIST_GAME_MENU_DOWN "GAME_MENU_DOWN"
#define ACTIONLIST_GAME_MENU_LEFT "GAME_MENU_LEFT"

const char* ActionList_GetAction(int32_t index);
IStringArray* ActionList_GetArray(void);

