/* Eolithic2
 * Copyright 2025-2026 Patrick Derosby
 * Released under the zlib License.
 * See eolithic2.LICENSE for details.
 */

 /* Derived from code by Ethan Lee (Copyright 2009-2024).
  * Released under the Microsoft Public License.
  * See fna.LICENSE for details.

  * Derived from code by the Mono.Xna Team (Copyright 2006).
  * Released under the MIT License.
  * See monoxna.LICENSE for details.
  */

#include "Keys.h"

const char* Keys_GetKeyName(Key key)
{
	switch (key)
	{
	case KEYS_None:
		return "None";
	case KEYS_Back:
		return "Back";
	case KEYS_Tab:
		return "Tab";
	case KEYS_Enter:
		return "Enter";
	case KEYS_Pause:
		return "Pause";
	case KEYS_CapsLock:
		return "CapsLock";
	case KEYS_Kana:
		return "Kana";
	case KEYS_Kanji:
		return "Kanji";
	case KEYS_Escape:
		return "Escape";
	case KEYS_ImeConvert:
		return "ImeConvert";
	case KEYS_ImeNoConvert:
		return "ImeNoConvert";
	case KEYS_Space:
		return "Space";
	case KEYS_PageUp:
		return "PageUp";
	case KEYS_PageDown:
		return "PageDown";
	case KEYS_End:
		return "End";
	case KEYS_Home:
		return "Home";
	case KEYS_Left:
		return "Left";
	case KEYS_Up:
		return "Up";
	case KEYS_Right:
		return "Right";
	case KEYS_Down:
		return "Down";
	case KEYS_Select:
		return "Select";
	case KEYS_Print:
		return "Print";
	case KEYS_Execute:
		return "Execute";
	case KEYS_PrintScreen:
		return "PrintScreen";
	case KEYS_Insert:
		return "Insert";
	case KEYS_Delete:
		return "Delete";
	case KEYS_Help:
		return "Help";
	case KEYS_D0:
		return "D0";
	case KEYS_D1:
		return "D1";
	case KEYS_D2:
		return "D2";
	case KEYS_D3:
		return "D3";
	case KEYS_D4:
		return "D4";
	case KEYS_D5:
		return "D5";
	case KEYS_D6:
		return "D6";
	case KEYS_D7:
		return "D7";
	case KEYS_D8:
		return "D8";
	case KEYS_D9:
		return "D9";
	case KEYS_A:
		return "A";
	case KEYS_B:
		return "B";
	case KEYS_C:
		return "C";
	case KEYS_D:
		return "D";
	case KEYS_E:
		return "E";
	case KEYS_F:
		return "F";
	case KEYS_G:
		return "G";
	case KEYS_H:
		return "H";
	case KEYS_I:
		return "I";
	case KEYS_J:
		return "J";
	case KEYS_K:
		return "K";
	case KEYS_L:
		return "L";
	case KEYS_M:
		return "M";
	case KEYS_N:
		return "N";
	case KEYS_O:
		return "O";
	case KEYS_P:
		return "P";
	case KEYS_Q:
		return "Q";
	case KEYS_R:
		return "R";
	case KEYS_S:
		return "S";
	case KEYS_T:
		return "T";
	case KEYS_U:
		return "U";
	case KEYS_V:
		return "V";
	case KEYS_W:
		return "W";
	case KEYS_X:
		return "X";
	case KEYS_Y:
		return "Y";
	case KEYS_Z:
		return "Z";
	case KEYS_LeftWindows:
		return "LeftWindows";
	case KEYS_RightWindows:
		return "RightWindows";
	case KEYS_Apps:
		return "Apps";
	case KEYS_Sleep:
		return "Sleep";
	case KEYS_NumPad0:
		return "NumPad0";
	case KEYS_NumPad1:
		return "NumPad1";
	case KEYS_NumPad2:
		return "NumPad2";
	case KEYS_NumPad3:
		return "NumPad3";
	case KEYS_NumPad4:
		return "NumPad4";
	case KEYS_NumPad5:
		return "NumPad5";
	case KEYS_NumPad6:
		return "NumPad6";
	case KEYS_NumPad7:
		return "NumPad7";
	case KEYS_NumPad8:
		return "NumPad8";
	case KEYS_NumPad9:
		return "NumPad9";
	case KEYS_Multiply:
		return "Multiply";
	case KEYS_Add:
		return "Add";
	case KEYS_Separator:
		return "Separator";
	case KEYS_Subtract:
		return "Subtract";
	case KEYS_Decimal:
		return "Decimal";
	case KEYS_Divide:
		return "Divide";
	case KEYS_F1:
		return "F1";
	case KEYS_F2:
		return "F2";
	case KEYS_F3:
		return "F3";
	case KEYS_F4:
		return "F4";
	case KEYS_F5:
		return "F5";
	case KEYS_F6:
		return "F6";
	case KEYS_F7:
		return "F7";
	case KEYS_F8:
		return "F8";
	case KEYS_F9:
		return "F9";
	case KEYS_F10:
		return "F10";
	case KEYS_F11:
		return "F11";
	case KEYS_F12:
		return "F12";
	case KEYS_F13:
		return "F13";
	case KEYS_F14:
		return "F14";
	case KEYS_F15:
		return "F15";
	case KEYS_F16:
		return "F16";
	case KEYS_F17:
		return "F17";
	case KEYS_F18:
		return "F18";
	case KEYS_F19:
		return "F19";
	case KEYS_F20:
		return "F20";
	case KEYS_F21:
		return "F21";
	case KEYS_F22:
		return "F22";
	case KEYS_F23:
		return "F23";
	case KEYS_F24:
		return "F24";
	case KEYS_NumLock:
		return "NumLock";
	case KEYS_Scroll:
		return "Scroll";
	case KEYS_LeftShift:
		return "LeftShift";
	case KEYS_RightShift:
		return "RightShift";
	case KEYS_LeftControl:
		return "LeftControl";
	case KEYS_RightControl:
		return "RightControl";
	case KEYS_LeftAlt:
		return "LeftAlt";
	case KEYS_RightAlt:
		return "RightAlt";
	case KEYS_BrowserBack:
		return "BrowserBack";
	case KEYS_BrowserForward:
		return "BrowserForward";
	case KEYS_BrowserRefresh:
		return "BrowserRefresh";
	case KEYS_BrowserStop:
		return "BrowserStop";
	case KEYS_BrowserSearch:
		return "BrowserSearch";
	case KEYS_BrowserFavorites:
		return "BrowserFavorites";
	case KEYS_BrowserHome:
		return "BrowserHome";
	case KEYS_VolumeMute:
		return "VolumeMute";
	case KEYS_VolumeDown:
		return "VolumeDown";
	case KEYS_VolumeUp:
		return "VolumeUp";
	case KEYS_MediaNextTrack:
		return "MediaNextTrack";
	case KEYS_MediaPreviousTrack:
		return "MediaPreviousTrack";
	case KEYS_MediaStop:
		return "MediaStop";
	case KEYS_MediaPlayPause:
		return "MediaPlayPause";
	case KEYS_LaunchMail:
		return "LaunchMail";
	case KEYS_SelectMedia:
		return "SelectMedia";
	case KEYS_LaunchApplication1:
		return "LaunchApplication1";
	case KEYS_LaunchApplication2:
		return "LaunchApplication2";
	case KEYS_OemSemicolon:
		return "OemSemicolon";
	case KEYS_OemPlus:
		return "OemPlus";
	case KEYS_OemComma:
		return "OemComma";
	case KEYS_OemMinus:
		return "OemMinus";
	case KEYS_OemPeriod:
		return "OemPeriod";
	case KEYS_OemQuestion:
		return "OemQuestion";
	case KEYS_OemTilde:
		return "OemTilde";
	case KEYS_ChatPadGreen:
		return "ChatPadGreen";
	case KEYS_ChatPadOrange:
		return "ChatPadOrange";
	case KEYS_OemOpenBrackets:
		return "OemOpenBrackets";
	case KEYS_OemPipe:
		return "OemPipe";
	case KEYS_OemCloseBrackets:
		return "OemCloseBrackets";
	case KEYS_OemQuotes:
		return "OemQuotes";
	case KEYS_Oem8:
		return "Oem8";
	case KEYS_OemBackslash:
		return "OemBackslash";
	case KEYS_ProcessKey:
		return "ProcessKey";
	case KEYS_OemCopy:
		return "OemCopy";
	case KEYS_OemAuto:
		return "OemAuto";
	case KEYS_OemEnlW:
		return "OemEnlW";
	case KEYS_Attn:
		return "Attn";
	case KEYS_Crsel:
		return "Crsel";
	case KEYS_Exsel:
		return "Exsel";
	case KEYS_EraseEof:
		return "EraseEof";
	case KEYS_Play:
		return "Play";
	case KEYS_Zoom:
		return "Zoom";
	case KEYS_Pa1:
		return "Pa1";
	case KEYS_OemClear:
		return "OemClear";
	}
	return "?";
}
